#!/usr/bin/env python3
"""Regenerate manual/SOURCE_TO_PDF_MAPPING.md from YAML manifests."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from manifest_index import (
    MANUAL_DIR,
    REPO_ROOT,
    build_source_index,
    iter_volume_file_entries,
    load_all_volumes,
)

OUTPUT_PATH = MANUAL_DIR / "SOURCE_TO_PDF_MAPPING.md"
GENERATED_MARKER = "<!-- generated by scripts/build_manual/generate_source_mapping.py -->"


def format_volume_section(vol: dict[str, Any], version: str) -> str:
    pdf = vol["pdf"]
    vol_id = vol["id"]
    title = vol.get("title", vol_id)
    lines = [
        f"## {pdf.replace('.pdf', '')} — {title}",
        "",
        f"**Interim directory:** `.build/manual/{version}/{vol_id}/`",
        "",
        "| Order | Source Markdown | Interim Markdown | Notes |",
        "|------:|-----------------|------------------|-------|",
    ]
    for entry in iter_volume_file_entries(vol, version):
        order = entry["order"]
        source = entry.get("source") or "*(generated)*"
        interim_name = Path(entry["interim"]).name
        interim = f"`{interim_name}`"
        notes = entry.get("notes") or ""
        if source != "*(generated)*":
            source = f"`{source}`"
        lines.append(f"| {order} | {source} | {interim} | {notes} |")
    lines.append("")
    return "\n".join(lines)


def format_multi_volume_table(index: dict[str, list]) -> str:
    multi = {src: entries for src, entries in index.items() if len(entries) > 1}
    if not multi:
        return ""
    lines = [
        "## Source files appearing in multiple PDFs",
        "",
        "| Source Markdown | PDF volumes |",
        "|-----------------|-------------|",
    ]
    for src in sorted(multi):
        pdfs = sorted({e["pdf"] for e in multi[src]})
        pdf_list = ", ".join(f"`{p}`" for p in pdfs)
        lines.append(f"| `{src}` | {pdf_list} |")
    lines.append("")
    return "\n".join(lines)


def generate(version: str) -> str:
    volumes = load_all_volumes()
    index = build_source_index(version)

    body_parts = [
        GENERATED_MARKER,
        "# Source Markdown to PDF mapping",
        "",
        "This document lists how repository Markdown sources flow through the "
        "manual build pipeline into release PDFs under "
        f"`dist/manual/{version}/`.",
        "",
        "**Authoritative manifests:** "
        "[`manifest.yaml`](manifest.yaml), "
        "[`trainers-manifest.yaml`](trainers-manifest.yaml), and "
        "[`students-manifest.yaml`](students-manifest.yaml). "
        "Regenerate this file after manifest changes:",
        "",
        "```bash",
        "python3 scripts/build_manual/generate_source_mapping.py",
        "```",
        "",
        "## Build pipeline",
        "",
        "```text",
        "docs/**/*.md  (source)",
        "      │",
        "      ▼  preprocess.py  (strip breadcrumbs, rewrite links, inject chapter anchors)",
        f".build/manual/{version}/{{volume_id}}/*.md  (interim, gitignored)",
        "      │",
        "      ▼  pandoc + LaTeX",
        f"dist/manual/{version}/*.pdf  (release)",
        "```",
        "",
        "| Stage | Location | Purpose |",
        "|-------|----------|---------|",
        "| Source | `docs/**/*.md` | Canonical documentation edited in GitHub / Obsidian |",
        "| Interim | `.build/manual/{version}/{volume_id}/` | Preprocessed Markdown cache per volume |",
        "| Release | `dist/manual/{version}/` | Published PDFs (tracked in git) |",
        "",
        f"Replace `{{version}}` with the CLI label (for example `{version}`).",
        "",
        "### Reverse lookup",
        "",
        "```bash",
        "python3 scripts/build_manual/lookup_source.py --pdf 02-Reference.pdf --section \"Concept Library\"",
        "python3 scripts/build_manual/lookup_source.py --source docs/Reference/Concept_Library.md",
        "```",
        "",
        "See [PDF maintainer workflow](MAINTAINER_WORKFLOW.md) for the full fix-and-rebuild process.",
        "",
        "---",
        "",
    ]

    for vol in volumes:
        body_parts.append(format_volume_section(vol, version))

    body_parts.append(format_multi_volume_table(index))

    body_parts.extend(
        [
            "## Sources not exported to PDF",
            "",
            "Repository paths outside the manual manifests remain source-only. "
            "See [`link_registry.yaml`](link_registry.yaml) for PDF link notes.",
            "",
            "## Related documents",
            "",
            "- [PDF maintainer workflow](MAINTAINER_WORKFLOW.md)",
            "- [PDF link resolution](PDF_LINKS.md)",
            "- [PDF manual build](../scripts/build_manual/README.md)",
            "- [PDF manual releases](../dist/manual/README.md)",
            "",
        ]
    )

    return "\n".join(body_parts)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SOURCE_TO_PDF_MAPPING.md")
    parser.add_argument("--version", default="2026.07", help="Release version label")
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print to stdout instead of writing manual/SOURCE_TO_PDF_MAPPING.md",
    )
    args = parser.parse_args()

    content = generate(args.version)
    if args.stdout:
        print(content)
        return

    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
